shopxemay/Controllers/NguoiDungController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using shopxemay.Models;

namespace Tuan4_1911252687_ToTrungKien.Controllers
{
    public class NguoiDungController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: NguoiDung
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["hoten"];
            var tendangnhap = collection["tendangnhap"];
            var matkhau = collection["matkhau"];
            var MatKhauXacNhan = collection["MatKhauXacNhan"];
            var email = collection["email"];
            var diachi = collection["diachi"];
            var dienthoai = collection["dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["ngaysinh"]);
            
            if (string.IsNullOrEmpty(tendangnhap))
            {
                ViewData["Loi1"] = "Tên đăng nhập không được để trống";
            }
            if (string.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Mật khẩu không được để trống";
            }
            if (string.IsNullOrEmpty(email))
            {
                ViewData["Loi3"] = "Email không được để trống";
            }
            if (string.IsNullOrEmpty(diachi))
            {
                ViewData["Loi4"] = "Địa chỉ không được để trống";
            }
            if (string.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi5"] = "Điện thoại không được để trống";
            }
            if (string.IsNullOrEmpty(hoten))
            {
                ViewData["Loi6"] = "Họ tên không được để trống";
            }
            if (String.IsNullOrEmpty(MatKhauXacNhan))
            {
                ViewData["Loi7"] = "Phải nhập mật khẩu xác nhận";
            }
            if (string.IsNullOrEmpty(ngaysinh))
            {
                ViewData["Loi8"] = "Ngày sinh không được để trống";
            }
            else
            {
                if (!matkhau.Equals(MatKhauXacNhan))
                {
                    ViewData["MatKhauGiongNhau"] = "Mật khẩu và mật khẩu xác nhận không giống nhau";
                }
                else
                {
                    var check = data.KhachHangs.FirstOrDefault(s => s.tendangnhap == tendangnhap);
                    if (check == null)
                    {
                        kh.hoten = hoten;
                        kh.tendangnhap = tendangnhap;
                        kh.matkhau = matkhau;
                        kh.email = email;
                        kh.diachi = diachi;
                        kh.dienthoai = dienthoai;
                        kh.ngaysinh = DateTime.Parse(ngaysinh);
                        data.KhachHangs.InsertOnSubmit(kh);
                        data.SubmitChanges();
                        return RedirectToAction("DangNhap");
                    }
                    else
                    {
                        ViewBag.ThongBao = "Tài khoản đã tồn tại !!!";
                        return View();
                    }
                    
                }
            }
            return this.DangKy();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendangnhap = collection["tendangnhap"];
            var matkhau = collection["matkhau"];
            KhachHang kh = data.KhachHangs.SingleOrDefault(n => n.tendangnhap == tendangnhap && n.matkhau == matkhau);
            if (kh != null)
            {
                ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                Session["TaiKhoan"] = kh;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
        public ActionResult DangXuat()
        {
            Session.Clear();
            return RedirectToAction("Index","Home");
        }
    }
}

shopxemay/Controllers/XeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shopxemay.Models;
namespace shopxemay.Controllers
{
    public class XeController : Controller
    {
        // GET: Xe
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult ListXe()
        {
            var all_Xe = from ss in data.Xes select ss;
            return View(all_Xe);
        
        }
        public ActionResult Detail(int id)
        {
            var D_Xe = data.Xes.Where(m => m.maxe == id).First();
            return View(D_Xe);
        }
        public ActionResult XeSo()
        {
            var xeso = data.Xes.Where(n => n.maloai == 1); 
            return View(xeso);
        }
        public ActionResult XeTayGa()
        {
            var xetayga = data.Xes.Where(n => n.maloai == 2);
            return View(xetayga);
        }
        public ActionResult XeConTay()
        {
            var xecontay = data.Xes.Where(n => n.maloai == 3);
            return View(xecontay);
        }
        public ActionResult XeMoTo()
        {
            var xemoto = data.Xes.Where(n => n.maloai == 4);
            return View(xemoto);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, Xe s)
        {
            var E_tenxe = collection["tenxe"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_tenxe))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tenxe = E_tenxe.ToString();
                s.hinh = E_hinh.ToString();
                s.giaban = E_giaban;
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                data.Xes.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("ListXe");
            }
            return this.Create();
        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/assets/images/" + file.FileName));
            return "/Content/assets/images/" + file.FileName;
        }
        public ActionResult Edit(int id)
        {
            var E_xe = data.Xes.First(m => m.maxe == id);
            return View(E_xe);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_xe = data.Xes.First(m => m.maxe == id);
            var E_tenxe = collection["tenxe"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            E_xe.maxe = id;
            if (string.IsNullOrEmpty(E_tenxe))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                E_xe.tenxe = E_tenxe;
                E_xe.hinh = E_hinh;
                E_xe.giaban = E_giaban;
                E_xe.ngaycapnhat = E_ngaycapnhat;
                E_xe.soluongton = E_soluongton;
                UpdateModel(E_xe);
                data.SubmitChanges();
                return RedirectToAction("ListXe");
            }
            return this.Edit(id);
        }

        public ActionResult Delete(int id)
        {
            var D_Xe = data.Xes.First(m => m.maxe == id);
            return View(D_Xe);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = data.Xes.Where(m => m.maxe == id).First();
            data.Xes.DeleteOnSubmit(D_sach);
            data.SubmitChanges();
            return RedirectToAction("ListXe");
        }

    }
}

shopxemay/Views/Shared/MyLayout.cshtml
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - motobike Shop</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    </body>
</html>
@RenderSection("upload", required: false)

shopxemay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>


<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/assets/fonts/fontawesome-free-6.1.1-web/css/all.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/base.css">
    <link rel="stylesheet" href="~/Content/assets/css/styles.css">

</head>

<body>
    <div class="main"></div>
        <header class="header">
            <div class="grid">
                <!-- navbar one -->
                <nav class="navbar">
                    <ul class="navbar-list">
                        <li class="navbar-item">@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                        <li class="navbar-item">PHỤ TÙNG</li>
                        <li class="navbar-item">@Html.ActionLink("Sản phẩm", "ListXe", "Xe")</li>
                        <li class="navbar-item">DỊCH VỤ</li>
                        <li class="navbar-item">TIN TỨC</li>
                        <li class="navbar-item">LIÊN HỆ</li>
                    </ul>
                    @if (Session["TaiKhoan"] == null)
                    {
                        <ul class="navbar-list">
                            <li class="navbar-item-DN_DK navbar-item navbar-item-separate">
                                <i class=" fa-solid fa-user"></i> @Html.ActionLink("đăng nhập", "DangNhap", "NguoiDung")
                            </li>
                            <li class="navbar-item-DN_DK navbar-item">
                                <i class="fa-solid fa-address-card"></i> @Html.ActionLink("Đăng Kí", "DangKy", "NguoiDung")
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-list">
                            <li class="navbar-item-DN_DK navbar-item">
                                <i class="fa-solid fa-address-card"></i> @Html.ActionLink("Đăng Xuất", "DangXuat", "NguoiDung")
                            </li>
                        </ul>
                    }
                </nav>
                <!-- navbar two -->
                <div class="navbar-second">
                    <div class="navbar-logo">
                        <img class="navbar-logo_img" src="assets/images/logo.png" alt="">
                    </div>
                    @using (Html.BeginForm("Index", "Home", FormMethod.Get, new { @class = "form-inline" }))
                    {<div class="navbar-search">
                            <input type="text" class="navbar-search-input" value="@ViewBag.Find" name="name" placeholder="Nhập từ khóa tìm kiếm">
                            <button class="navbar-search-btn">
                                <i type="navbar-search-btn-icon fa-solid fa-magnifying-glass" @*class="navbar-search-btn-icon fa-solid fa-magnifying-glass"*@></i>
                            </button>
                        </div>}

                    <div class="navbar-favorite">
                        <i class="navbar-favorite-icon fa-solid fa-heart"></i>
                        <p class="navbar-favorite-text">Yêu thích</p>
                    </div>

                    <div class="navbar-cart">
                        <i class="navbar-cart-icon fa-solid fa-cart-shopping"></i>
                        <p class="navbar-cart-text">@Html.Partial("~/Views/GioHang/GioHangPartial.cshtml")</p>
                    </div>
                    <div class="navbar-help">
                        <i class="navbar-help-icon fa-solid fa-circle-question"></i>
                        <p class="navbar--help-text">Hỗ Trợ</p>
                    </div>
                </div>
            </div>
        </header>




        <div class="container body-content">
            @RenderBody()

            <footer>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        @RenderSection("changeImageauto", required: false)
</body>
</html>
@RenderSection("upload", required: false)